services:
  hegemonikon:
    build: .
    container_name: hegemonikon
    volumes:
      - .:/home/jovyan/work
    working_dir: /home/jovyan/work
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - GRANT_SUDO=yes
