# Minimal configuration for 6-parameter NES model
output_dir: "./results/roberts_npe_minimal"
run_id: "roberts_npe_minimal"

experiment:
  name: "roberts_npe_minimal"
  random_seed: 42
  n_train_simulations: 1000
  n_sbc_datasets: 100
  n_posterior_samples: 200
  n_template_trials: 100

data:
  processed_data: "./data/roberts_processed.csv"
  n_participants: 45
  n_trials_per_participant: 285

model:
  name: "MVNES"
  # Parameters with their default values (will be overridden by priors during sampling)
  parameters:
    v_norm: 1.0
    a_0: 1.0
    w_s_eff: 1.0
    t_0: 0.3
    alpha_gain: 0.8
    beta_val: 0.0
  
  # Fixed parameters
  fixed_parameters:
    logit_z0: 0.0
    log_tau_norm: 0.0

npe:
  training:
    max_epochs: 50
    batch_size: 256
    learning_rate: 0.0005
    validation_fraction: 0.1
    early_stopping_patience: 10
  inference:
    num_samples: 500
    num_workers: 4
    sample_method: "mcmc"

summary_stats:
  rt_bins: [0.1, 0.3, 0.5, 0.7, 0.9]
  conditions:
    - frame: "gain"
      cond: "tc"
    - frame: "loss"
      cond: "tc"
    - frame: "gain"
      cond: "ntc"
    - frame: "loss"
      cond: "ntc"

logging:
  level: "INFO"
  file: "nes_copilot.log"
  console: true
  filemode: "w"
